/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectKeyRouteImport } from './routes/projects/$projectKey'
import { Route as ProjectsProjectKeyIndexRouteImport } from './routes/projects/$projectKey/index'
import { Route as ProjectsProjectKeySettingsRouteImport } from './routes/projects/$projectKey/settings'
import { Route as ProjectsProjectKeyIssuesRouteImport } from './routes/projects/$projectKey/issues'
import { Route as ProjectsProjectKeyBoardRouteImport } from './routes/projects/$projectKey/board'
import { Route as ProjectsProjectKeyBacklogRouteImport } from './routes/projects/$projectKey/backlog'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectKeyRoute = ProjectsProjectKeyRouteImport.update({
  id: '/$projectKey',
  path: '/$projectKey',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectKeyIndexRoute = ProjectsProjectKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectKeyRoute,
} as any)
const ProjectsProjectKeySettingsRoute =
  ProjectsProjectKeySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectKeyRoute,
  } as any)
const ProjectsProjectKeyIssuesRoute =
  ProjectsProjectKeyIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => ProjectsProjectKeyRoute,
  } as any)
const ProjectsProjectKeyBoardRoute = ProjectsProjectKeyBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ProjectsProjectKeyRoute,
} as any)
const ProjectsProjectKeyBacklogRoute =
  ProjectsProjectKeyBacklogRouteImport.update({
    id: '/backlog',
    path: '/backlog',
    getParentRoute: () => ProjectsProjectKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectKey': typeof ProjectsProjectKeyRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectKey/backlog': typeof ProjectsProjectKeyBacklogRoute
  '/projects/$projectKey/board': typeof ProjectsProjectKeyBoardRoute
  '/projects/$projectKey/issues': typeof ProjectsProjectKeyIssuesRoute
  '/projects/$projectKey/settings': typeof ProjectsProjectKeySettingsRoute
  '/projects/$projectKey/': typeof ProjectsProjectKeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectKey/backlog': typeof ProjectsProjectKeyBacklogRoute
  '/projects/$projectKey/board': typeof ProjectsProjectKeyBoardRoute
  '/projects/$projectKey/issues': typeof ProjectsProjectKeyIssuesRoute
  '/projects/$projectKey/settings': typeof ProjectsProjectKeySettingsRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectKey': typeof ProjectsProjectKeyRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectKey/backlog': typeof ProjectsProjectKeyBacklogRoute
  '/projects/$projectKey/board': typeof ProjectsProjectKeyBoardRoute
  '/projects/$projectKey/issues': typeof ProjectsProjectKeyIssuesRoute
  '/projects/$projectKey/settings': typeof ProjectsProjectKeySettingsRoute
  '/projects/$projectKey/': typeof ProjectsProjectKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/$projectKey'
    | '/projects/'
    | '/projects/$projectKey/backlog'
    | '/projects/$projectKey/board'
    | '/projects/$projectKey/issues'
    | '/projects/$projectKey/settings'
    | '/projects/$projectKey/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/projects/$projectKey/backlog'
    | '/projects/$projectKey/board'
    | '/projects/$projectKey/issues'
    | '/projects/$projectKey/settings'
    | '/projects/$projectKey'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/projects/$projectKey'
    | '/projects/'
    | '/projects/$projectKey/backlog'
    | '/projects/$projectKey/board'
    | '/projects/$projectKey/issues'
    | '/projects/$projectKey/settings'
    | '/projects/$projectKey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectKey': {
      id: '/projects/$projectKey'
      path: '/$projectKey'
      fullPath: '/projects/$projectKey'
      preLoaderRoute: typeof ProjectsProjectKeyRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectKey/': {
      id: '/projects/$projectKey/'
      path: '/'
      fullPath: '/projects/$projectKey/'
      preLoaderRoute: typeof ProjectsProjectKeyIndexRouteImport
      parentRoute: typeof ProjectsProjectKeyRoute
    }
    '/projects/$projectKey/settings': {
      id: '/projects/$projectKey/settings'
      path: '/settings'
      fullPath: '/projects/$projectKey/settings'
      preLoaderRoute: typeof ProjectsProjectKeySettingsRouteImport
      parentRoute: typeof ProjectsProjectKeyRoute
    }
    '/projects/$projectKey/issues': {
      id: '/projects/$projectKey/issues'
      path: '/issues'
      fullPath: '/projects/$projectKey/issues'
      preLoaderRoute: typeof ProjectsProjectKeyIssuesRouteImport
      parentRoute: typeof ProjectsProjectKeyRoute
    }
    '/projects/$projectKey/board': {
      id: '/projects/$projectKey/board'
      path: '/board'
      fullPath: '/projects/$projectKey/board'
      preLoaderRoute: typeof ProjectsProjectKeyBoardRouteImport
      parentRoute: typeof ProjectsProjectKeyRoute
    }
    '/projects/$projectKey/backlog': {
      id: '/projects/$projectKey/backlog'
      path: '/backlog'
      fullPath: '/projects/$projectKey/backlog'
      preLoaderRoute: typeof ProjectsProjectKeyBacklogRouteImport
      parentRoute: typeof ProjectsProjectKeyRoute
    }
  }
}

interface ProjectsProjectKeyRouteChildren {
  ProjectsProjectKeyBacklogRoute: typeof ProjectsProjectKeyBacklogRoute
  ProjectsProjectKeyBoardRoute: typeof ProjectsProjectKeyBoardRoute
  ProjectsProjectKeyIssuesRoute: typeof ProjectsProjectKeyIssuesRoute
  ProjectsProjectKeySettingsRoute: typeof ProjectsProjectKeySettingsRoute
  ProjectsProjectKeyIndexRoute: typeof ProjectsProjectKeyIndexRoute
}

const ProjectsProjectKeyRouteChildren: ProjectsProjectKeyRouteChildren = {
  ProjectsProjectKeyBacklogRoute: ProjectsProjectKeyBacklogRoute,
  ProjectsProjectKeyBoardRoute: ProjectsProjectKeyBoardRoute,
  ProjectsProjectKeyIssuesRoute: ProjectsProjectKeyIssuesRoute,
  ProjectsProjectKeySettingsRoute: ProjectsProjectKeySettingsRoute,
  ProjectsProjectKeyIndexRoute: ProjectsProjectKeyIndexRoute,
}

const ProjectsProjectKeyRouteWithChildren =
  ProjectsProjectKeyRoute._addFileChildren(ProjectsProjectKeyRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectKeyRoute: typeof ProjectsProjectKeyRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectKeyRoute: ProjectsProjectKeyRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
