/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as AdminHotelsHotelIdRouteImport } from './routes/admin.hotels.$hotelId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHotelsHotelIdRoute = AdminHotelsHotelIdRouteImport.update({
  id: '/admin/hotels/$hotelId',
  path: '/admin/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/admin': typeof AdminIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/login'
    | '/register'
    | '/search'
    | '/bookings/$bookingId'
    | '/hotels/$hotelId'
    | '/admin/'
    | '/bookings/'
    | '/admin/hotels/$hotelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/login'
    | '/register'
    | '/search'
    | '/bookings/$bookingId'
    | '/hotels/$hotelId'
    | '/admin'
    | '/bookings'
    | '/admin/hotels/$hotelId'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/login'
    | '/register'
    | '/search'
    | '/bookings/$bookingId'
    | '/hotels/$hotelId'
    | '/admin/'
    | '/bookings/'
    | '/admin/hotels/$hotelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  AdminHotelsHotelIdRoute: typeof AdminHotelsHotelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hotels/$hotelId': {
      id: '/admin/hotels/$hotelId'
      path: '/admin/hotels/$hotelId'
      fullPath: '/admin/hotels/$hotelId'
      preLoaderRoute: typeof AdminHotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  AdminHotelsHotelIdRoute: AdminHotelsHotelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
