/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiderHistoryRouteImport } from './routes/rider/history'
import { Route as DriverHistoryRouteImport } from './routes/driver/history'
import { Route as DriverEarningsRouteImport } from './routes/driver/earnings'

const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderHistoryRoute = RiderHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => RiderRoute,
} as any)
const DriverHistoryRoute = DriverHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rider': typeof RiderRouteWithChildren
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/rider/history': typeof RiderHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rider': typeof RiderRouteWithChildren
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/rider/history': typeof RiderHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rider': typeof RiderRouteWithChildren
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/rider/history': typeof RiderHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/driver'
    | '/login'
    | '/register'
    | '/rider'
    | '/driver/earnings'
    | '/driver/history'
    | '/rider/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/driver'
    | '/login'
    | '/register'
    | '/rider'
    | '/driver/earnings'
    | '/driver/history'
    | '/rider/history'
  id:
    | '__root__'
    | '/'
    | '/driver'
    | '/login'
    | '/register'
    | '/rider'
    | '/driver/earnings'
    | '/driver/history'
    | '/rider/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriverRoute: typeof DriverRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RiderRoute: typeof RiderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/history': {
      id: '/rider/history'
      path: '/history'
      fullPath: '/rider/history'
      preLoaderRoute: typeof RiderHistoryRouteImport
      parentRoute: typeof RiderRoute
    }
    '/driver/history': {
      id: '/driver/history'
      path: '/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverHistoryRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
  }
}

interface DriverRouteChildren {
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverHistoryRoute: typeof DriverHistoryRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverEarningsRoute: DriverEarningsRoute,
  DriverHistoryRoute: DriverHistoryRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface RiderRouteChildren {
  RiderHistoryRoute: typeof RiderHistoryRoute
}

const RiderRouteChildren: RiderRouteChildren = {
  RiderHistoryRoute: RiderHistoryRoute,
}

const RiderRouteWithChildren = RiderRoute._addFileChildren(RiderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriverRoute: DriverRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RiderRoute: RiderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
