/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopShopSlugRouteImport } from './routes/shop.$shopSlug'
import { Route as SellerDashboardRouteImport } from './routes/seller/dashboard'
import { Route as SellerCreateShopRouteImport } from './routes/seller/create-shop'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as CategoryCategorySlugRouteImport } from './routes/category.$categorySlug'
import { Route as SellerProductsNewRouteImport } from './routes/seller/products.new'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopShopSlugRoute = ShopShopSlugRouteImport.update({
  id: '/shop/$shopSlug',
  path: '/shop/$shopSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerCreateShopRoute = SellerCreateShopRouteImport.update({
  id: '/seller/create-shop',
  path: '/seller/create-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugRoute = CategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductsNewRoute = SellerProductsNewRouteImport.update({
  id: '/seller/products/new',
  path: '/seller/products/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/create-shop': typeof SellerCreateShopRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/shop/$shopSlug': typeof ShopShopSlugRoute
  '/seller/products/new': typeof SellerProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/create-shop': typeof SellerCreateShopRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/shop/$shopSlug': typeof ShopShopSlugRoute
  '/seller/products/new': typeof SellerProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/create-shop': typeof SellerCreateShopRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/shop/$shopSlug': typeof ShopShopSlugRoute
  '/seller/products/new': typeof SellerProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/orders'
    | '/register'
    | '/search'
    | '/category/$categorySlug'
    | '/product/$productId'
    | '/seller/create-shop'
    | '/seller/dashboard'
    | '/shop/$shopSlug'
    | '/seller/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/orders'
    | '/register'
    | '/search'
    | '/category/$categorySlug'
    | '/product/$productId'
    | '/seller/create-shop'
    | '/seller/dashboard'
    | '/shop/$shopSlug'
    | '/seller/products/new'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/orders'
    | '/register'
    | '/search'
    | '/category/$categorySlug'
    | '/product/$productId'
    | '/seller/create-shop'
    | '/seller/dashboard'
    | '/shop/$shopSlug'
    | '/seller/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  SellerCreateShopRoute: typeof SellerCreateShopRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  ShopShopSlugRoute: typeof ShopShopSlugRoute
  SellerProductsNewRoute: typeof SellerProductsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$shopSlug': {
      id: '/shop/$shopSlug'
      path: '/shop/$shopSlug'
      fullPath: '/shop/$shopSlug'
      preLoaderRoute: typeof ShopShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/create-shop': {
      id: '/seller/create-shop'
      path: '/seller/create-shop'
      fullPath: '/seller/create-shop'
      preLoaderRoute: typeof SellerCreateShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/products/new': {
      id: '/seller/products/new'
      path: '/seller/products/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof SellerProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  SellerCreateShopRoute: SellerCreateShopRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  ShopShopSlugRoute: ShopShopSlugRoute,
  SellerProductsNewRoute: SellerProductsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
