/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerRepoRouteImport } from './routes/$owner.$repo'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner.$repo.pulls'
import { Route as OwnerRepoIssuesRouteImport } from './routes/$owner.$repo.issues'
import { Route as OwnerRepoDiscussionsRouteImport } from './routes/$owner.$repo.discussions'
import { Route as OwnerRepoPullNumberRouteImport } from './routes/$owner.$repo.pull.$number'
import { Route as OwnerRepoIssuesNumberRouteImport } from './routes/$owner.$repo.issues.$number'
import { Route as OwnerRepoTreeBranchSplatRouteImport } from './routes/$owner.$repo.tree.$branch.$'
import { Route as OwnerRepoBlobBranchSplatRouteImport } from './routes/$owner.$repo.blob.$branch.$'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoRoute = OwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoIssuesRoute = OwnerRepoIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoDiscussionsRoute = OwnerRepoDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPullNumberRoute = OwnerRepoPullNumberRouteImport.update({
  id: '/pull/$number',
  path: '/pull/$number',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoIssuesNumberRoute = OwnerRepoIssuesNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => OwnerRepoIssuesRoute,
} as any)
const OwnerRepoTreeBranchSplatRoute =
  OwnerRepoTreeBranchSplatRouteImport.update({
    id: '/tree/$branch/$',
    path: '/tree/$branch/$',
    getParentRoute: () => OwnerRepoRoute,
  } as any)
const OwnerRepoBlobBranchSplatRoute =
  OwnerRepoBlobBranchSplatRouteImport.update({
    id: '/blob/$branch/$',
    path: '/blob/$branch/$',
    getParentRoute: () => OwnerRepoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/$owner/$repo/discussions': typeof OwnerRepoDiscussionsRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/$owner/$repo/blob/$branch/$': typeof OwnerRepoBlobBranchSplatRoute
  '/$owner/$repo/tree/$branch/$': typeof OwnerRepoTreeBranchSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/$owner/$repo/discussions': typeof OwnerRepoDiscussionsRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/$owner/$repo/blob/$branch/$': typeof OwnerRepoBlobBranchSplatRoute
  '/$owner/$repo/tree/$branch/$': typeof OwnerRepoTreeBranchSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/$owner/$repo/discussions': typeof OwnerRepoDiscussionsRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/issues/$number': typeof OwnerRepoIssuesNumberRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRoute
  '/$owner/$repo/blob/$branch/$': typeof OwnerRepoBlobBranchSplatRoute
  '/$owner/$repo/tree/$branch/$': typeof OwnerRepoTreeBranchSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/new'
    | '/register'
    | '/search'
    | '/$owner/$repo'
    | '/$owner/$repo/discussions'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/pull/$number'
    | '/$owner/$repo/blob/$branch/$'
    | '/$owner/$repo/tree/$branch/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/new'
    | '/register'
    | '/search'
    | '/$owner/$repo'
    | '/$owner/$repo/discussions'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/pull/$number'
    | '/$owner/$repo/blob/$branch/$'
    | '/$owner/$repo/tree/$branch/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/new'
    | '/register'
    | '/search'
    | '/$owner/$repo'
    | '/$owner/$repo/discussions'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/pull/$number'
    | '/$owner/$repo/blob/$branch/$'
    | '/$owner/$repo/tree/$branch/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  OwnerRepoRoute: typeof OwnerRepoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/issues': {
      id: '/$owner/$repo/issues'
      path: '/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof OwnerRepoIssuesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/discussions': {
      id: '/$owner/$repo/discussions'
      path: '/discussions'
      fullPath: '/$owner/$repo/discussions'
      preLoaderRoute: typeof OwnerRepoDiscussionsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pull/$number': {
      id: '/$owner/$repo/pull/$number'
      path: '/pull/$number'
      fullPath: '/$owner/$repo/pull/$number'
      preLoaderRoute: typeof OwnerRepoPullNumberRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/issues/$number': {
      id: '/$owner/$repo/issues/$number'
      path: '/$number'
      fullPath: '/$owner/$repo/issues/$number'
      preLoaderRoute: typeof OwnerRepoIssuesNumberRouteImport
      parentRoute: typeof OwnerRepoIssuesRoute
    }
    '/$owner/$repo/tree/$branch/$': {
      id: '/$owner/$repo/tree/$branch/$'
      path: '/tree/$branch/$'
      fullPath: '/$owner/$repo/tree/$branch/$'
      preLoaderRoute: typeof OwnerRepoTreeBranchSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/blob/$branch/$': {
      id: '/$owner/$repo/blob/$branch/$'
      path: '/blob/$branch/$'
      fullPath: '/$owner/$repo/blob/$branch/$'
      preLoaderRoute: typeof OwnerRepoBlobBranchSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
  }
}

interface OwnerRepoIssuesRouteChildren {
  OwnerRepoIssuesNumberRoute: typeof OwnerRepoIssuesNumberRoute
}

const OwnerRepoIssuesRouteChildren: OwnerRepoIssuesRouteChildren = {
  OwnerRepoIssuesNumberRoute: OwnerRepoIssuesNumberRoute,
}

const OwnerRepoIssuesRouteWithChildren = OwnerRepoIssuesRoute._addFileChildren(
  OwnerRepoIssuesRouteChildren,
)

interface OwnerRepoRouteChildren {
  OwnerRepoDiscussionsRoute: typeof OwnerRepoDiscussionsRoute
  OwnerRepoIssuesRoute: typeof OwnerRepoIssuesRouteWithChildren
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRoute
  OwnerRepoPullNumberRoute: typeof OwnerRepoPullNumberRoute
  OwnerRepoBlobBranchSplatRoute: typeof OwnerRepoBlobBranchSplatRoute
  OwnerRepoTreeBranchSplatRoute: typeof OwnerRepoTreeBranchSplatRoute
}

const OwnerRepoRouteChildren: OwnerRepoRouteChildren = {
  OwnerRepoDiscussionsRoute: OwnerRepoDiscussionsRoute,
  OwnerRepoIssuesRoute: OwnerRepoIssuesRouteWithChildren,
  OwnerRepoPullsRoute: OwnerRepoPullsRoute,
  OwnerRepoPullNumberRoute: OwnerRepoPullNumberRoute,
  OwnerRepoBlobBranchSplatRoute: OwnerRepoBlobBranchSplatRoute,
  OwnerRepoTreeBranchSplatRoute: OwnerRepoTreeBranchSplatRoute,
}

const OwnerRepoRouteWithChildren = OwnerRepoRoute._addFileChildren(
  OwnerRepoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  OwnerRepoRoute: OwnerRepoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
