/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsTopicRouteImport } from './routes/topics.$topic'
import { Route as StoryStoryIdRouteImport } from './routes/story.$storyId'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicRoute = TopicsTopicRouteImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdRoute = StoryStoryIdRouteImport.update({
  id: '/story/$storyId',
  path: '/story/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/topics': typeof TopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/search'
    | '/settings'
    | '/trending'
    | '/story/$storyId'
    | '/topics/$topic'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/search'
    | '/settings'
    | '/trending'
    | '/story/$storyId'
    | '/topics/$topic'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/search'
    | '/settings'
    | '/trending'
    | '/story/$storyId'
    | '/topics/$topic'
    | '/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TrendingRoute: typeof TrendingRoute
  StoryStoryIdRoute: typeof StoryStoryIdRoute
  TopicsTopicRoute: typeof TopicsTopicRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topic': {
      id: '/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/topics/$topic'
      preLoaderRoute: typeof TopicsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId': {
      id: '/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/story/$storyId'
      preLoaderRoute: typeof StoryStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TrendingRoute: TrendingRoute,
  StoryStoryIdRoute: StoryStoryIdRoute,
  TopicsTopicRoute: TopicsTopicRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
