/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigningDeclinedRouteImport } from './routes/signing-declined'
import { Route as SigningCompleteRouteImport } from './routes/signing-complete'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnvelopesIndexRouteImport } from './routes/envelopes/index'
import { Route as SignAccessTokenRouteImport } from './routes/sign/$accessToken'
import { Route as EnvelopesNewRouteImport } from './routes/envelopes/new'
import { Route as EnvelopesEnvelopeIdRouteImport } from './routes/envelopes/$envelopeId'

const SigningDeclinedRoute = SigningDeclinedRouteImport.update({
  id: '/signing-declined',
  path: '/signing-declined',
  getParentRoute: () => rootRouteImport,
} as any)
const SigningCompleteRoute = SigningCompleteRouteImport.update({
  id: '/signing-complete',
  path: '/signing-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvelopesIndexRoute = EnvelopesIndexRouteImport.update({
  id: '/envelopes/',
  path: '/envelopes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignAccessTokenRoute = SignAccessTokenRouteImport.update({
  id: '/sign/$accessToken',
  path: '/sign/$accessToken',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvelopesNewRoute = EnvelopesNewRouteImport.update({
  id: '/envelopes/new',
  path: '/envelopes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvelopesEnvelopeIdRoute = EnvelopesEnvelopeIdRouteImport.update({
  id: '/envelopes/$envelopeId',
  path: '/envelopes/$envelopeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signing-complete': typeof SigningCompleteRoute
  '/signing-declined': typeof SigningDeclinedRoute
  '/envelopes/$envelopeId': typeof EnvelopesEnvelopeIdRoute
  '/envelopes/new': typeof EnvelopesNewRoute
  '/sign/$accessToken': typeof SignAccessTokenRoute
  '/envelopes/': typeof EnvelopesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signing-complete': typeof SigningCompleteRoute
  '/signing-declined': typeof SigningDeclinedRoute
  '/envelopes/$envelopeId': typeof EnvelopesEnvelopeIdRoute
  '/envelopes/new': typeof EnvelopesNewRoute
  '/sign/$accessToken': typeof SignAccessTokenRoute
  '/envelopes': typeof EnvelopesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signing-complete': typeof SigningCompleteRoute
  '/signing-declined': typeof SigningDeclinedRoute
  '/envelopes/$envelopeId': typeof EnvelopesEnvelopeIdRoute
  '/envelopes/new': typeof EnvelopesNewRoute
  '/sign/$accessToken': typeof SignAccessTokenRoute
  '/envelopes/': typeof EnvelopesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/signing-complete'
    | '/signing-declined'
    | '/envelopes/$envelopeId'
    | '/envelopes/new'
    | '/sign/$accessToken'
    | '/envelopes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/signing-complete'
    | '/signing-declined'
    | '/envelopes/$envelopeId'
    | '/envelopes/new'
    | '/sign/$accessToken'
    | '/envelopes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/signing-complete'
    | '/signing-declined'
    | '/envelopes/$envelopeId'
    | '/envelopes/new'
    | '/sign/$accessToken'
    | '/envelopes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SigningCompleteRoute: typeof SigningCompleteRoute
  SigningDeclinedRoute: typeof SigningDeclinedRoute
  EnvelopesEnvelopeIdRoute: typeof EnvelopesEnvelopeIdRoute
  EnvelopesNewRoute: typeof EnvelopesNewRoute
  SignAccessTokenRoute: typeof SignAccessTokenRoute
  EnvelopesIndexRoute: typeof EnvelopesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signing-declined': {
      id: '/signing-declined'
      path: '/signing-declined'
      fullPath: '/signing-declined'
      preLoaderRoute: typeof SigningDeclinedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signing-complete': {
      id: '/signing-complete'
      path: '/signing-complete'
      fullPath: '/signing-complete'
      preLoaderRoute: typeof SigningCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envelopes/': {
      id: '/envelopes/'
      path: '/envelopes'
      fullPath: '/envelopes/'
      preLoaderRoute: typeof EnvelopesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$accessToken': {
      id: '/sign/$accessToken'
      path: '/sign/$accessToken'
      fullPath: '/sign/$accessToken'
      preLoaderRoute: typeof SignAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envelopes/new': {
      id: '/envelopes/new'
      path: '/envelopes/new'
      fullPath: '/envelopes/new'
      preLoaderRoute: typeof EnvelopesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envelopes/$envelopeId': {
      id: '/envelopes/$envelopeId'
      path: '/envelopes/$envelopeId'
      fullPath: '/envelopes/$envelopeId'
      preLoaderRoute: typeof EnvelopesEnvelopeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SigningCompleteRoute: SigningCompleteRoute,
  SigningDeclinedRoute: SigningDeclinedRoute,
  EnvelopesEnvelopeIdRoute: EnvelopesEnvelopeIdRoute,
  EnvelopesNewRoute: EnvelopesNewRoute,
  SignAccessTokenRoute: SignAccessTokenRoute,
  EnvelopesIndexRoute: EnvelopesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
