/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantDashboardRouteImport } from './routes/restaurant-dashboard'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverDashboardRouteImport } from './routes/driver-dashboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as RestaurantRestaurantIdRouteImport } from './routes/restaurant.$restaurantId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'

const RestaurantDashboardRoute = RestaurantDashboardRouteImport.update({
  id: '/restaurant-dashboard',
  path: '/restaurant-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/driver-dashboard',
  path: '/driver-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRestaurantIdRoute = RestaurantRestaurantIdRouteImport.update({
  id: '/restaurant/$restaurantId',
  path: '/restaurant/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/driver-dashboard': typeof DriverDashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/restaurant-dashboard': typeof RestaurantDashboardRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/driver-dashboard': typeof DriverDashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/restaurant-dashboard': typeof RestaurantDashboardRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/driver-dashboard': typeof DriverDashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/restaurant-dashboard': typeof RestaurantDashboardRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/driver-dashboard'
    | '/login'
    | '/register'
    | '/restaurant-dashboard'
    | '/orders/$orderId'
    | '/restaurant/$restaurantId'
    | '/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/driver-dashboard'
    | '/login'
    | '/register'
    | '/restaurant-dashboard'
    | '/orders/$orderId'
    | '/restaurant/$restaurantId'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/driver-dashboard'
    | '/login'
    | '/register'
    | '/restaurant-dashboard'
    | '/orders/$orderId'
    | '/restaurant/$restaurantId'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  DriverDashboardRoute: typeof DriverDashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RestaurantDashboardRoute: typeof RestaurantDashboardRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  RestaurantRestaurantIdRoute: typeof RestaurantRestaurantIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurant-dashboard': {
      id: '/restaurant-dashboard'
      path: '/restaurant-dashboard'
      fullPath: '/restaurant-dashboard'
      preLoaderRoute: typeof RestaurantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-dashboard': {
      id: '/driver-dashboard'
      path: '/driver-dashboard'
      fullPath: '/driver-dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$restaurantId': {
      id: '/restaurant/$restaurantId'
      path: '/restaurant/$restaurantId'
      fullPath: '/restaurant/$restaurantId'
      preLoaderRoute: typeof RestaurantRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  DriverDashboardRoute: DriverDashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RestaurantDashboardRoute: RestaurantDashboardRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  RestaurantRestaurantIdRoute: RestaurantRestaurantIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
