/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegmentIdRouteImport } from './routes/segment.$id'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'
import { Route as ProfileIdFollowingRouteImport } from './routes/profile.$id.following'
import { Route as ProfileIdFollowersRouteImport } from './routes/profile.$id.followers'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentIdRoute = SegmentIdRouteImport.update({
  id: '/segment/$id',
  path: '/segment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdFollowingRoute = ProfileIdFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => ProfileIdRoute,
} as any)
const ProfileIdFollowersRoute = ProfileIdFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => ProfileIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/segments': typeof SegmentsRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/activity/$id': typeof ActivityIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/segment/$id': typeof SegmentIdRoute
  '/profile/$id/followers': typeof ProfileIdFollowersRoute
  '/profile/$id/following': typeof ProfileIdFollowingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/segments': typeof SegmentsRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/activity/$id': typeof ActivityIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/segment/$id': typeof SegmentIdRoute
  '/profile/$id/followers': typeof ProfileIdFollowersRoute
  '/profile/$id/following': typeof ProfileIdFollowingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/segments': typeof SegmentsRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/activity/$id': typeof ActivityIdRoute
  '/profile/$id': typeof ProfileIdRouteWithChildren
  '/segment/$id': typeof SegmentIdRoute
  '/profile/$id/followers': typeof ProfileIdFollowersRoute
  '/profile/$id/following': typeof ProfileIdFollowingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/register'
    | '/segments'
    | '/stats'
    | '/upload'
    | '/activity/$id'
    | '/profile/$id'
    | '/segment/$id'
    | '/profile/$id/followers'
    | '/profile/$id/following'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/login'
    | '/register'
    | '/segments'
    | '/stats'
    | '/upload'
    | '/activity/$id'
    | '/profile/$id'
    | '/segment/$id'
    | '/profile/$id/followers'
    | '/profile/$id/following'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/login'
    | '/register'
    | '/segments'
    | '/stats'
    | '/upload'
    | '/activity/$id'
    | '/profile/$id'
    | '/segment/$id'
    | '/profile/$id/followers'
    | '/profile/$id/following'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SegmentsRoute: typeof SegmentsRoute
  StatsRoute: typeof StatsRoute
  UploadRoute: typeof UploadRoute
  ActivityIdRoute: typeof ActivityIdRoute
  ProfileIdRoute: typeof ProfileIdRouteWithChildren
  SegmentIdRoute: typeof SegmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segment/$id': {
      id: '/segment/$id'
      path: '/segment/$id'
      fullPath: '/segment/$id'
      preLoaderRoute: typeof SegmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id/following': {
      id: '/profile/$id/following'
      path: '/following'
      fullPath: '/profile/$id/following'
      preLoaderRoute: typeof ProfileIdFollowingRouteImport
      parentRoute: typeof ProfileIdRoute
    }
    '/profile/$id/followers': {
      id: '/profile/$id/followers'
      path: '/followers'
      fullPath: '/profile/$id/followers'
      preLoaderRoute: typeof ProfileIdFollowersRouteImport
      parentRoute: typeof ProfileIdRoute
    }
  }
}

interface ProfileIdRouteChildren {
  ProfileIdFollowersRoute: typeof ProfileIdFollowersRoute
  ProfileIdFollowingRoute: typeof ProfileIdFollowingRoute
}

const ProfileIdRouteChildren: ProfileIdRouteChildren = {
  ProfileIdFollowersRoute: ProfileIdFollowersRoute,
  ProfileIdFollowingRoute: ProfileIdFollowingRoute,
}

const ProfileIdRouteWithChildren = ProfileIdRoute._addFileChildren(
  ProfileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SegmentsRoute: SegmentsRoute,
  StatsRoute: StatsRoute,
  UploadRoute: UploadRoute,
  ActivityIdRoute: ActivityIdRoute,
  ProfileIdRoute: ProfileIdRouteWithChildren,
  SegmentIdRoute: SegmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
