/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MeetingTypesRouteImport } from './routes/meeting-types'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as BookMeetingTypeIdRouteImport } from './routes/book.$meetingTypeId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingTypesRoute = MeetingTypesRouteImport.update({
  id: '/meeting-types',
  path: '/meeting-types',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => BookingsRoute,
} as any)
const BookMeetingTypeIdRoute = BookMeetingTypeIdRouteImport.update({
  id: '/book/$meetingTypeId',
  path: '/book/$meetingTypeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meeting-types': typeof MeetingTypesRoute
  '/register': typeof RegisterRoute
  '/book/$meetingTypeId': typeof BookMeetingTypeIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meeting-types': typeof MeetingTypesRoute
  '/register': typeof RegisterRoute
  '/book/$meetingTypeId': typeof BookMeetingTypeIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meeting-types': typeof MeetingTypesRoute
  '/register': typeof RegisterRoute
  '/book/$meetingTypeId': typeof BookMeetingTypeIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/availability'
    | '/bookings'
    | '/dashboard'
    | '/login'
    | '/meeting-types'
    | '/register'
    | '/book/$meetingTypeId'
    | '/bookings/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/availability'
    | '/bookings'
    | '/dashboard'
    | '/login'
    | '/meeting-types'
    | '/register'
    | '/book/$meetingTypeId'
    | '/bookings/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/availability'
    | '/bookings'
    | '/dashboard'
    | '/login'
    | '/meeting-types'
    | '/register'
    | '/book/$meetingTypeId'
    | '/bookings/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvailabilityRoute: typeof AvailabilityRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MeetingTypesRoute: typeof MeetingTypesRoute
  RegisterRoute: typeof RegisterRoute
  BookMeetingTypeIdRoute: typeof BookMeetingTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-types': {
      id: '/meeting-types'
      path: '/meeting-types'
      fullPath: '/meeting-types'
      preLoaderRoute: typeof MeetingTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/book/$meetingTypeId': {
      id: '/book/$meetingTypeId'
      path: '/book/$meetingTypeId'
      fullPath: '/book/$meetingTypeId'
      preLoaderRoute: typeof BookMeetingTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookingsRouteChildren {
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsBookingIdRoute: BookingsBookingIdRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvailabilityRoute: AvailabilityRoute,
  BookingsRoute: BookingsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MeetingTypesRoute: MeetingTypesRoute,
  RegisterRoute: RegisterRoute,
  BookMeetingTypeIdRoute: BookMeetingTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
