/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SendRouteImport } from './routes/send'
import { Route as RequestRouteImport } from './routes/request'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/send': typeof SendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/send': typeof SendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/send': typeof SendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/login'
    | '/payment-methods'
    | '/register'
    | '/request'
    | '/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/login'
    | '/payment-methods'
    | '/register'
    | '/request'
    | '/send'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/login'
    | '/payment-methods'
    | '/register'
    | '/request'
    | '/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  LoginRoute: typeof LoginRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  RegisterRoute: typeof RegisterRoute
  RequestRoute: typeof RequestRoute
  SendRoute: typeof SendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  LoginRoute: LoginRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  RegisterRoute: RegisterRoute,
  RequestRoute: RequestRoute,
  SendRoute: SendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
