/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppIdPreviewRouteImport } from './routes/app.$appId.preview'
import { Route as AppAppIdEditRouteImport } from './routes/app.$appId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIdPreviewRoute = AppAppIdPreviewRouteImport.update({
  id: '/app/$appId/preview',
  path: '/app/$appId/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIdEditRoute = AppAppIdEditRouteImport.update({
  id: '/app/$appId/edit',
  path: '/app/$appId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/$appId/edit': typeof AppAppIdEditRoute
  '/app/$appId/preview': typeof AppAppIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/$appId/edit': typeof AppAppIdEditRoute
  '/app/$appId/preview': typeof AppAppIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/$appId/edit': typeof AppAppIdEditRoute
  '/app/$appId/preview': typeof AppAppIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/app/$appId/edit'
    | '/app/$appId/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/app/$appId/edit' | '/app/$appId/preview'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/app/$appId/edit'
    | '/app/$appId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AppAppIdEditRoute: typeof AppAppIdEditRoute
  AppAppIdPreviewRoute: typeof AppAppIdPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$appId/preview': {
      id: '/app/$appId/preview'
      path: '/app/$appId/preview'
      fullPath: '/app/$appId/preview'
      preLoaderRoute: typeof AppAppIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$appId/edit': {
      id: '/app/$appId/edit'
      path: '/app/$appId/edit'
      fullPath: '/app/$appId/edit'
      preLoaderRoute: typeof AppAppIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AppAppIdEditRoute: AppAppIdEditRoute,
  AppAppIdPreviewRoute: AppAppIdPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
